### ISSUE TITLE
Bring back the typewriter effect

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#10]
Rotate these below on the landing page:
Researchers
Software developers
Clinicians 
Surgeons  
Students 
Faculty
Postdocs

**Comment by shansitads** [comment]
Typewriter reference: https://github.com/soumyajit4419/Portfolio
Style might already be in style.css

**Comment by mashcodes10** [comment]
Where should be the Typewriter? Right after "Welcome to BrainHack Vanderbilt" ?

**Comment by shansitads** [comment]
For the time being you can put it there with the same font size as the date

@rgbayrak is that the idea you had for it?

**Comment by rgbayrak** [comment]
@mashcodes10 

right under or over the date (play with it to see which one looks better? same size as the date sounds good. 

Make a static "Open to" _in white_ and rotating list _in purple_
Researchers
Software Developers
Clinicians
Surgeons
Data Scientists
Students
Faculty
Postdocs


So it reads
Open to Researchers
Open to Software Developers
....
