### ISSUE TITLE
FAQs tab

### ISSUE THREAD

**Issue by shansitads** [brainhack-vandy/brainhack-vandy.github.io#11]
- [x] Create a separate tab for FAQs in the navigation bar
- [x] Create dropdown style FAQs

**Comment by rgbayrak** [comment]
do we have a style picked for dropdown style? pls have a visual attached to this issue's PR.

**Comment by rgbayrak** [comment]
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

<img width="721" alt="Screenshot 2024-10-29 at 6 42 21 PM" src="https://github.com/user-attachments/assets/3de444a5-6aa8-4ddb-a4f7-cb83c9d40973">
<img width="710" alt="Screenshot 2024-10-29 at 6 42 17 PM" src="https://github.com/user-attachments/assets/3d6285a4-39cb-44e3-9634-00d25e39f92b">


See the style above, this is kind of the vision I had with the dropdown menus! 

(also this makes me think, mkdocs-material is very versatile and cool. In case if you wanted to potentially not have to design every aspect of the website, you could consider their template @shansitads)

**Comment by shansitads** [comment]
The dropdown style we're following seems to be called an accordion. These resource for create a React Accordion could be useful:
https://www.npmjs.com/package/react-faq-component
https://react-bootstrap.netlify.app/docs/components/accordion/
https://mui.com/material-ui/react-accordion/
