### ISSUE TITLE
Sponsors section

### ISSUE THREAD

**Issue by shansitads** [brainhack-vandy/brainhack-vandy.github.io#12]
- [x] Create a sponsors section in the landing page
- [x] Refer to sponsor icons on last year's archived website
- [x] Format follows template’s professional skillset grid

**Comment by rgbayrak** [comment]
Let's make sure the sponsor icons are svg if not, we can figure out a way to give them transparent bg.

**Comment by shansitads** [comment]
Current version

- [ ] Need to select sponsor to change icons to white for
- [ ] Need to split the rows better (or make the container less wide)
<img width="1443" alt="Screenshot 2024-11-15 at 8 45 01 PM" src="https://github.com/user-attachments/assets/a39e5b6e-b3f0-45b8-8c50-c819b16d8eb2">

@rgbayrak

**Comment by rgbayrak** [comment]
re: (in the landing page above the location section) Sponsors (titled "2024 Sponsors", we will replace these with this years when we have them and archive the old ones)

**Comment by rgbayrak** [comment]
#34 closes this issue
