### ISSUE TITLE
Schedule tab

### ISSUE THREAD

**Issue by shansitads** [brainhack-vandy/brainhack-vandy.github.io#13]
- [ ] Create a schedule calendar in a separate tab
- [ ] Add schedule tab to nav bar

**Comment by rgbayrak** [comment]
See https://brainhackwestern.github.io/#schedule

**Comment by shansitads** [comment]
Resources:
- Brainhack website code: https://github.com/pvandyken/brainhack_western_test_site/tree/master/src/components/schedule (it's in typescript but you can convert it to react)
- The template website: https://github.com/soumyajit4419/Portfolio
- I've shared our 2025 schedule on google drive
- Meeting notes: https://docs.google.com/document/d/1xVths0MQZQ_cvqUNrqCwpfd9VUs1xxS1oKORF4SEL6A/edit?usp=sharing

Things to keep in mind:
- [ ] Add a navbar link to the schedule tab (you can choose an icon from `react-icons` for the navbar
- [ ] Add a route to the schedule tab in `App.js` similar to how the project tab has one

Another note: We don't edit the deployed branch bcs that's generated by git!

**Comment by shansitads** [comment]
I added a modification of the navbar icon and ordering of tabs in the feature/schedule branch
Other changes needed

- Setup/Cleanup can be removed from the schedule since that is the organizer's task
- TrainTrack schedule items have to be added
- Schedule needs to follow a calendar-style format similar to the BrainHack western website code shared:

<img width="1503" alt="Screenshot 2024-11-11 at 3 03 58 PM" src="https://github.com/user-attachments/assets/9b223415-5bfe-495c-8b66-eb4237915510">

**Comment by rgbayrak** [comment]
![image](https://github.com/user-attachments/assets/a3fe260c-c852-422e-8826-c0c72b72468c)
Based on the latest implementation. 
- Add an ability to include hyperlinks 
- Enlarge font size + match row sizes to the font (body of text) size so there is no empty space in the blocks (this can be adaptable width stays the same but length changes based on content)
- unconferences (2 of them) is off by 30 mins to the main workshops (e.g. 2pm and 2:30 pm start time), no overlap
- color choices can be more happy and bright
- Spell out the days and month; Friday, Saturday etc.  (there is empty space in these column headers no reason to abbreviate)
- Title: Tentative (in white) Event Schedule (in purple)

@shansitads

**Comment by shansitads** [comment]
- Added an ability to include hyperlinks, indicated by the arrows
- Increased font sizes
- Fixed unconference timings
- Brighter color palette 
- spelled out days of the week
- "tentative" added to title
- reduced scrollyness (no more scroll bar inside the calendar itself)
<img width="1334" alt="Screenshot 2024-12-05 at 12 58 23 AM" src="https://github.com/user-attachments/assets/41e7fe2e-d071-4aa4-9285-7020dbf95987">

**Comment by shansitads** [comment]
@rgbayrak deploying this!

<img width="1057" alt="Screenshot 2024-12-05 at 12 57 02 PM" src="https://github.com/user-attachments/assets/245368e6-ae73-4fe6-a930-224c13eaf31a">
