### ISSUE TITLE
Package vulnerabilities

### ISSUE THREAD

**Issue by shansitads** [brainhack-vandy/brainhack-vandy.github.io#14]
- [ ] Check npm package vulnerabilities and warnings for any concerning security issues marked by dependabot
- [ ] Resolve issues by changing versions/replacing the packages

**Comment by rgbayrak** [comment]
@shansitads @dgzct11 any update on this?

**Comment by shansitads** [comment]
I was able to get the npm vulnerabilities down to 13 with `npm audit fix` and down to 8 with `npm update`, still looking into the remaining ones

**Comment by dgzct11** [comment]
It seems that react-scripts is the cause of all the vulnerabilities. I found this github issue that explains how these aren't 'true' vulnerabilities (https://github.com/facebook/create-react-app/issues/11174), and after moving react-scripts to the devDependencies and running `npm auit --omit=dev` it says 0 vulnerabilities.
