### ISSUE TITLE
Team tab

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#22]
Similar to this: https://ohbm.github.io/hackathon2023/team/

We can grab frames from canva.

**Comment by rgbayrak** [comment]
mocked a few frames on canva, let me know the one you like, I will add the team visuals to assets for this tab. 

<img width="1057" alt="Screenshot 2024-11-20 at 10 56 35 AM" src="https://github.com/user-attachments/assets/581762c7-6493-4f74-99a4-ad8d270414f9">

**Comment by rgbayrak** [comment]
ignore the second column, second row, dunno what happened there.

**Comment by goodalse2019** [comment]
My favorites are 4, 6, or 8!

**Comment by rgbayrak** [comment]
Re from @shansitads >> You can work on the team tab – we don't have pictures of all the organizers yet but you can create a branch with placeholders similar to the format of the linked reference website
