### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#27]
- [x] Move all styling to style.css
- [x] Remove pushed branches

**Comment by shansitads** [comment]
Done for schedule and typewriter. TBD: check other files

**Comment by rgbayrak** [comment]
Can you explain what has been done for this PR (during the cleanup) in details? @shansitads 

We should probably do this for all issues. @dgzct11 @mashcodes10

**Comment by shansitads** [comment]
- removed duplicate components
- removed duplicate images and streamlined all into public/assets
- organized styling into page-wise css files for tabs with a lot of styling code
- combined index.css and style.css into index.css
- all common css styles remain in index.css


(copied from the PR message)
