### ISSUE TITLE
Link registration button to registration form 

### ISSUE THREAD

**Issue by richardwsong** [brainhack-vandy/brainhack-vandy.github.io#31]
Registration form link: https://docs.google.com/forms/d/e/1FAIpQLSeX6AfQ0noO5hzIEO-SgBIcfsHfCuQyyEgLGxrP3N5UCg8w0w/viewform?usp=sharing 

Needs to be done by Monday! 

@shansitads

**Comment by shansitads** [comment]
Button should be called "Apply Here" and made clickable (you can refer to other buttons in the website too)
