### ISSUE TITLE
README with how to PR

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#4]
e.g. Developers locally render website before opening a PR and reviewers do the same when reviewing PRs. Running the npm start command, giving a localhost preview.

**Comment by shansitads** [comment]
Added setup, localhost preview and contribution instructions to the README in commit `#857d5bd`

**Comment by shansitads** [comment]
Added setup, localhost preview and contribution instructions to the README in commit `#857d5bd`
