### ISSUE TITLE
projects tab

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#8]
brief info (1 paragraph)
link to github issue
link to data (if available)

>> follow the template if project does not have image, use an image with matching design/style

**Comment by rgbayrak** [comment]
Shorter text to go with projects:  

"2024": [
      {
        title: "PhysioQA",
        description: `A nifty deep-learning tool to automate quality assessment of physiological signals. It's like having a friendly expert on your team, making sure your research data is as good as it can be!`
        github link: https://github.com/brainhack-vandy/projects/blob/main/2024/physioQA.md
      },
      {
        title: "Resting State Networks Across Age",
        description: `Resting state networks point to a characteristic of mental disorders, it is important to model how they change across age. We will compare methods to understand how resting state networks are retrieved and potentially model how they change across age.`,
      },
      {
        title: "fMRI-EEG Preprocessing",
        description: `Preprocessing is a critical step in neuroimaging analysis, laying the foundation for accurate and meaningful scientific discoveries. We will configure a pipeline to quality check for multiple datasets.`,
      },
      {
        title: "BIDS derivatives",
        description: `Derivatives structure and requirements for physiological data (i.e. cardiac, respiratory, blood pressure, etc.) are not yet covered by the BIDS specification. With this project, we hope to start a discussion around an eventual BIDS proposal on physiological derivatives.`
      },
      {
        title: "Neural Manifolds",
        description: `We present a population of simultaneously-recorded neurons from the non-human primate during learning of a complex sequence memory task, and in sleep afterwards. These data are exceptionally rich for exploration, but also to address three fundamental questions.`
      },

**Comment by rgbayrak** [comment]
Project Pitches
https://youtu.be/Cu4kU7bE-JA

**Comment by shansitads** [comment]
- [x] Project pitch instructions
- [x] Project pitch youtube video
- [x] Shortened 2024 project descriptions
- [x] 2024 project github links
- [x] 2024 project images
